### ISSUE TITLE
How to use with request-promise-native

### ISSUE THREAD

**Issue by rickerd** [akhoury/request-promise-cache#5]
I depend on request-promise-native but still i want to use this cache library, is this possible?

**Comment by akhoury** [comment]
I wouldn't use both, either use this lib `request-promise-cache` which already uses the __native__ Promise by default, __OR__ use `request-promise-native` with your own caching logic, the cache lib i use here is https://github.com/akhoury/nano-cache. 

If you use version [`2.0.0`](https://www.npmjs.com/package/request-promise-cache) of this lib (which I just published and added `resolveWithFullResponse` option), keep in mind that it doesn't support "verbs" sugar functions, like `request.get()` or `request.post()`, you have to do it the original way, as in 

```javascript
request({ url: '...', type: 'post' ... }).then().catch()
```

**Comment by rickerd** [comment]
Thanks for your reply and explanation.
The sugar verbs is what i do use and why it maybe didn't work for what i was trying.

Maybe you can make a new release/tag on Github?

**Comment by akhoury** [comment]
sure https://github.com/akhoury/request-promise-cache/releases/tag/2.0.0
